# Docker Compose for Large Trace Streaming Testing
# Tests Phase 4.4 streaming evaluation capabilities

services:
  # OpenTelemetry Collector with large trace configuration
  otelcol:
    build:
      context: ../shared
      dockerfile: Dockerfile.otelcol
    volumes:
      - ./config/otelcol-config.yaml:/etc/otelcol/config.yaml:ro
      - traces-output:/tmp
    ports:
      - "4317:4317"  # OTLP gRPC
      - "4318:4318"  # OTLP HTTP
      - "8888:8888"  # Prometheus metrics
      - "8889:8889"  # Internal telemetry
    environment:
      - OTEL_LOG_LEVEL=info
    depends_on:
      - minio
    mem_limit: 1g  # Generous memory for large traces
    cpus: 2.0

  # MinIO for S3-compatible storage
  minio:
    image: minio/minio:RELEASE.2024-01-01T16-36-33Z
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    command: server /data --console-address ":9001"
    volumes:
      - minio-data:/data
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3

  # MinIO client to create bucket
  createbucket:
    image: minio/mc:RELEASE.2024-01-01T05-03-17Z
    depends_on:
      minio:
        condition: service_healthy
    entrypoint: >
      /bin/sh -c "
      /usr/bin/mc alias set myminio http://minio:9000 minioadmin minioadmin;
      /usr/bin/mc mb myminio/large-traces-test;
      /usr/bin/mc policy set public myminio/large-traces-test;
      exit 0;
      "

  # Large trace generator
  trace-generator:
    build:
      context: ../object-only/generator
      dockerfile: Dockerfile
    environment:
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://otelcol:4317
      - OTEL_EXPORTER_OTLP_INSECURE=true
      - TRACE_SIZE=large        # Generate large traces
      - SPAN_COUNT=15000        # 15k spans per trace (triggers streaming)
      - TRACE_COUNT=10          # 10 large traces
      - SERVICES=5              # 5 different services
      - DURATION_SECONDS=300    # 5 minute test
    depends_on:
      - otelcol

volumes:
  minio-data:
  traces-output: