# Redis + S3 Integration Test
# Tests distributed tail sampling with Redis coordination and S3 spillover

include:
  - ../shared/docker-compose.services.yml

services:
  otelcol:
    image: otelcontribcol:latest
    ports:
      - "4317:4317"  # OTLP gRPC
      - "4318:4318"  # OTLP HTTP
      - "8888:8888"  # Prometheus metrics
      - "8889:8889"  # Prometheus metrics (alternate)
    volumes:
      - ./config:/config:ro
    command: ["--config=/config/otelcol-config.yaml"]
    depends_on:
      redis:
        condition: service_healthy
      minio-setup:
        condition: service_completed_successfully
    environment:
      - OTEL_LOG_LEVEL=debug
      - REDIS_ENDPOINT=redis:6379
      - S3_ENDPOINT=http://minio:9000
      - S3_BUCKET=tail-sampling-test
      - AWS_ACCESS_KEY_ID=minioadmin
      - AWS_SECRET_ACCESS_KEY=minioadmin123

  # Test runner with S3-specific scenarios
  test-runner:
    image: alpine:latest
    depends_on:
      - otelcol
    volumes:
      - ./tests:/tests:ro
    command: >
      /bin/sh -c "
      echo 'Running Redis + S3 integration tests...';
      apk add --no-cache curl jq aws-cli;
      cd /tests;
      ./run-tests.sh redis-s3;
      "

volumes:
  redis-data:
  minio-data: