# Docker Compose for Minimal Memory Testing
# Tests processor under severe memory constraints (Cloud Run 256MB scenarios)

services:
  # OpenTelemetry Collector with minimal memory
  otelcol:
    image: otelcontribcol:latest
    volumes:
      - ./config/otelcol-config.yaml:/etc/otelcol/config.yaml:ro
      - traces-output:/tmp
    ports:
      - "4317:4317"  # OTLP gRPC
      - "4318:4318"  # OTLP HTTP
      - "8888:8888"  # Prometheus metrics
      - "8889:8889"  # Internal telemetry
    environment:
      - OTEL_LOG_LEVEL=error  # Minimal logging
      - GOMAXPROCS=1
      - GOMEMLIMIT=128MiB     # Go memory limit
    command: ["--config=/etc/otelcol/config.yaml"]
    depends_on:
      - minio
    mem_limit: 128m  # Very constrained memory
    cpus: 0.5        # Limited CPU
    oom_kill_disable: false  # Allow OOM testing

  # Lightweight MinIO
  minio:
    image: minio/minio:RELEASE.2025-07-23T15-54-02Z
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin123
    command: server /data --console-address ":9001"
    volumes:
      - minio-data:/data
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3

  # Create bucket
  createbucket:
    image: minio/mc:RELEASE.2025-07-21T05-28-08Z
    depends_on:
      minio:
        condition: service_healthy
    entrypoint: >
      /bin/sh -c "
      /usr/bin/mc alias set myminio http://minio:9000 minioadmin minioadmin123;
      /usr/bin/mc mb myminio/minimal-memory-test;
      exit 0;
      "

  # Controlled trace generator
  trace-generator:
    image: telemetrygen:latest
    command: [
      "traces",
      "--otlp-endpoint", "otelcol:4317",
      "--otlp-insecure",
      "--duration", "300s",
      "--rate", "10",
      "--traces", "1000",
      "--child-spans", "5",
      "--service", "test-service"
    ]
    depends_on:
      - otelcol

volumes:
  minio-data:
  traces-output: